# Generated by Django 4.2 on 2023-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.FileField(upload_to="images"),
        ),
    ]
