# Generated by Django 4.2 on 2023-05-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_image_name_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="data",
            new_name="date",
        ),
    ]
